# framework_bt/viewer.py
"""
bt-view  ─ quick viewer for Parquet files generated by bt-extract

Usage:
    bt-view                    # detects utxos_*.parquet in the current directory
    bt-view --prefix foo       # searches for foo_*.parquet
    bt-view --head 20          # displays the first 20 rows
"""

from pathlib import Path
import click
import pyarrow.parquet as pq
import pandas as pd

SATOSHI = 100_000_000  # for converting to BTC


@click.command()
@click.option("--prefix", default="utxos", show_default=True,
              help="Prefix of the Parquet files to list")
@click.option("--head", default=10, show_default=True,
              help="Number of rows to display")
def main(prefix: str, head: int):
    files = sorted(Path(".").glob(f"{prefix}_*.parquet"))
    if not files:
        click.echo(f"No {prefix}_*.parquet files found in the current directory.")
        return

    click.echo("Files found:")
    for idx, f in enumerate(files, 1):
        size_mb = f.stat().st_size / 1_048_576
        click.echo(f"  [{idx}] {f.name:<30} {size_mb:6.1f} MB")

    choice = click.prompt("Select a file number", type=click.IntRange(1, len(files)))
    sel = files[choice - 1]

    click.echo(f"\nOpening {sel.name} …")
    table = pq.read_table(sel)
    df = table.to_pandas()

    # quick view
    click.echo(df.head(head).to_string(index=False))

    # ── summary ─────────────────────────────────────────────
    total_rows   = len(df)
    total_value  = df["value"].sum() / SATOSHI        # → BTC
    size_mb      = sel.stat().st_size / 1_048_576

    click.echo("\nSummary:")
    click.echo(f"  ▸ total rows         : {total_rows:,}")
    click.echo(f"  ▸ total value        : {total_value:,.8f} BTC")
    click.echo(f"  ▸ file size          : {size_mb:.1f} MB")

    # distribution by type
    click.echo("\n  Distribution by 'type':")
    dist = (
        df.groupby("type")
          .agg(count=("type", "size"), sats=("value", "sum"))
          .sort_values("count", ascending=False)
    )
    dist["btc"] = dist["sats"] / SATOSHI
    dist = dist.drop(columns="sats")
    click.echo(dist.to_string())

    click.echo("\nDone.")


if __name__ == "__main__":
    main()
